name: Mirror Repository to SecureAIAutonomyLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
    
      - name: Mirror repository to another private GitHub repo
        env:
            MIRROR_GITHUB_PAT: ${{ secrets.MIRROR_GITHUB_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git push --mirror "https://${MIRROR_GITHUB_PAT}@github.com/SecureAIAutonomyLab/codablellm-mirror.git"
